// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LargeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeRequest) Reset()         { *m = LargeRequest{} }
func (m *LargeRequest) String() string { return proto.CompactTextString(m) }
func (*LargeRequest) ProtoMessage()    {}
func (*LargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{0}
}

func (m *LargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeRequest.Unmarshal(m, b)
}
func (m *LargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeRequest.Marshal(b, m, deterministic)
}
func (m *LargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeRequest.Merge(m, src)
}
func (m *LargeRequest) XXX_Size() int {
	return xxx_messageInfo_LargeRequest.Size(m)
}
func (m *LargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LargeRequest proto.InternalMessageInfo

type LargeResponse struct {
	Large                []byte   `protobuf:"bytes,1,opt,name=Large,proto3" json:"Large,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeResponse) Reset()         { *m = LargeResponse{} }
func (m *LargeResponse) String() string { return proto.CompactTextString(m) }
func (*LargeResponse) ProtoMessage()    {}
func (*LargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{1}
}

func (m *LargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeResponse.Unmarshal(m, b)
}
func (m *LargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeResponse.Marshal(b, m, deterministic)
}
func (m *LargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeResponse.Merge(m, src)
}
func (m *LargeResponse) XXX_Size() int {
	return xxx_messageInfo_LargeResponse.Size(m)
}
func (m *LargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LargeResponse proto.InternalMessageInfo

func (m *LargeResponse) GetLarge() []byte {
	if m != nil {
		return m.Large
	}
	return nil
}

func init() {
	proto.RegisterType((*LargeRequest)(nil), "proto.test.LargeRequest")
	proto.RegisterType((*LargeResponse)(nil), "proto.test.LargeResponse")
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor_fc70169f84046e97) }

var fileDescriptor_fc70169f84046e97 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x33, 0x85, 0xb8, 0xc0, 0x94, 0x1e, 0x48, 0x44,
	0x89, 0x8f, 0x8b, 0xc7, 0x27, 0xb1, 0x28, 0x3d, 0x35, 0x28, 0xb5, 0xb0, 0x14, 0xc4, 0x57, 0xe5,
	0xe2, 0x85, 0xf2, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0x02, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x91, 0x2f, 0x17, 0x77, 0x48, 0x6a, 0x71, 0x49,
	0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1d, 0x54, 0x91, 0x90, 0x84, 0x1e, 0xc2, 0x6c,
	0x3d, 0x64, 0x83, 0xa5, 0x24, 0xb1, 0xc8, 0x40, 0xac, 0x50, 0x62, 0x70, 0x62, 0x8f, 0x62, 0x05,
	0xcb, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x9c, 0x14, 0x39,
	0xb5, 0x00, 0x00, 0x00,
}
